server:
  port: 8011

---

logging:
  level:
    com.ping: debug

jasypt:
  encryptor:
    # 加密盐值
    password: 123qwer
    # 加密算法设置 3.0.0 以后
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator

#context.listener.classes=com.ping.wechat.ApplicationEventListener
---

spring:

  profiles:
    active: local
  application:
    name: wechat

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ENC(ZNEkxeiG0CYAsRL1b71ptg==)
    password: ENC(SFJFGar3UoW0WKSXGkT3sQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
